baseURL = 'https://cmplx-xyttmt.github.io/'
languageCode = 'en-us'
paginate = 5
title = 'cmplx-xyttmt'
theme = 'paper'

[params]
    color = 'linen'
    twitter = "IsaacOwomugisha"
    github = 'cmplx-xyttmt'
    linkedin = 'owomugisha-isaac-32807912a'

    avatar = "https://avatars.githubusercontent.com/u/26762336?s=400&u=897a77ff678657345a82d196b192f2fd8fcaca06&v=4"
    name = "Hello, I'm Isaac Owomugisha"
    bio = "Software engineer and perpetual learner. I like digging into CS and math for fun: algorithms, distributed systems, graphics, performance engineering, and AI. This site is where I explore and write about what I learn."
    math = true

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "resume"
        name = "Resumé"
        url = "/resume/"
        weight = 10
#    [[menu.main]]
#        identifier = "algorithms"
#        name = "Algo Log"
#        url = "/algorithms/"
#        weight = 10
