baseURL = 'https://cmplx-xyttmt.github.io/'
languageCode = 'en-us'
paginate = 5
title = 'cmplx-xyttmt'
theme = 'paper'

[params]
    color = 'linen'
    twitter = "IsaacOwomugisha"
    github = 'cmplx-xyttmt'
    linkedin = 'owomugisha-isaac-32807912a'

    avatar = "https://avatars.githubusercontent.com/u/26762336?s=400&u=897a77ff678657345a82d196b192f2fd8fcaca06&v=4"
    name = "Hello, I'm Isaac Owomugisha"
    bio = "I build software and explore CS & math. Some of my areas of interest are: algorithms, distributed systems, graphics, performance engineering and AI. This site is my playground to explore and write about these interests. I'm also obsessed with efficient learning and building a project to help users actively engage with knowledge and truly master new skills."

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "resume"
        name = "Resumé"
        url = "/resume/"
        weight = 10
